// Generated by Wrangler on Tue Apr 09 2024 16:19:16 GMT+1200 (New Zealand Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  kv: KVNamespace;
  DB: D1Database;
  VECTORIZE_INDEX: VectorizeIndex;
  AI: unknown;
}
