name = "done"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

# [vars]
# MY_VARIABLE = "production_value"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "yc"
database_id = "c6c8017e-a835-4d8b-a07c-b24033f51e28"

[[kv_namespaces]]
binding = "kv"
id = "181ed1e82f1c4cf39c8f40e30a2aeb6c"


[ai]
binding = "AI"


[[vectorize]]
binding = "VECTORIZE_INDEX" # available within your Worker on env.VECTORIZE_INDEX
index_name = "ycindex"